### ISSUE TITLE
How to enable FEM for nRF21540DK

### ISSUE THREAD

**Issue by FHFS** [openthread/ot-nrf528xx#219]
Hello,

I've successfully built the firmware, and I am running otbr docker container. I can connect other devices to the thread network.

However, I am running on a nrf21540DK and I am seeing low RSSI values for my connection. I'm sure this is because of the FEM configuration.

I don't see any documentation for running on the nRF21540DK or for enabling the FEM.

1. I have tried enabling the PLATFORM_FEM_ENABLE_DEFAULT_CONFIG define in the platform-config.h for the nrf52840.

2. changed the PA/LNA/PDN pins in fem.c and nrf_fem_config.h to 19/22/23 respectively. I believe I have the correct pins, but I'm not sure.

Can anyone help me out here?

**Comment by LuDuda** [comment]
Hello @FHFS 

Support for nRF21540 is available through our official SDK called [nRF Connect SDK](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_thread.html).
OpenThread is part of the SDK and you can create both RCP or full-Thread type of devices.

[Here](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_radio_fem.html) you can find the instruction on how to enable nRF21540 FEM for any of the available samples or your custom application.

Low RSSI is expected on nRF21540 on vanilla OpenThread repository as there is no full support for this variant of FEM there.
