### ISSUE TITLE
Problem with attaching devices

### ISSUE THREAD

**Issue by BAzili073** [openthread/ot-nrf528xx#343]
Hello.
We use nRF52840 as devices. And use a RPi as a border router.
We had a problem of joining attaching devices to the network. 
Device may attach and may not depending on which  device's Parent Response it will receive last: if it's ot-br on RPi it attaches fine, if it's another device then child ID response from it never arrives so attach timeouts.

During the debug, we found out that disabling  OPENTHREAD_CONFIG_DROP_MESSAGE_ON_FRAGMENT_TX_FAILURE for the device that sends Child ID response helped to attaching device finally receive Id responce and enter the network

What is the the root of a problem and is this the correct solution?

[dev1_fail_to_dev2_succ_to_Rpi.log](https://github.com/openthread/openthread/files/8861762/dev1_fail_to_dev2_succ_to_Rpi.log)
[dev1_succ_to_dev.log](https://github.com/openthread/openthread/files/8861763/dev1_succ_to_dev.log)
[dev1_fail.log](https://github.com/openthread/openthread/files/8861764/dev1_fail.log)
[dev2_succ.log](https://github.com/openthread/openthread/files/8861765/dev2_succ.log)
[dev2_fail.log](https://github.com/openthread/openthread/files/8861766/dev2_fail.log)

**Comment by jwhui** [comment]
From the logs, it appears that there are many transmission failures with no-ack errors. This could be due to poor RF connectivity between the devices.

Which nRF52840 devices are you using? What is the received signal strength being reported for received messages in the OpenThread logs on the RPi?

**Comment by BAzili073** [comment]
Thanks for such fast answer!
We use devices of our own production based on nRF52840
Here is the log from RPi.
[RPi.log](https://github.com/openthread/ot-nrf528xx/files/8866909/RPi.log)
 | PAN  | MAC Address      | Ch | dBm | LQI |
+------+------------------+----+-----+-----+
| f0c6 | 02925165732a45d4 | 11 | -50 | 172 |
| f0c6 | a6678815ccf4d899 | 11 | -46 | 184 |
| f0c6 | e6fd73c544781877 | 11 | -60 | 124 |
| f0c6 | bafd8b412e0d32cd | 11 | -55 | 148 |

**Comment by jwhui** [comment]
@BAzili073 , do you have any nRF52840-DK or USB dongles to test with? It would be interesting to see if you can replicate the issue with Nordic dev boards.

**Comment by BAzili073** [comment]
Yeah, we will try to reproduce it on nRF52840-DK

**Comment by jwhui** [comment]
Closing stale issue.
