### ISSUE TITLE
Adafruit Feather nRF52840 not shown as USB Device

### ISSUE THREAD

**Issue by fklement** [openthread/ot-nrf528xx#397]
After I have successfully flashed the hex file to the device, it no longer appears on my Mac.

Flashing works fine:
```
>> nrfjprog -f nrf52 --chiperase --program ot-cli-ftd.hex --reset --verify                                                                                     ✔
Parsing image file.
Verifying programming.
Verified OK.
Applying system reset.
Run.
```

Before flashing open thread the feather device shows up under my `/dev/tty*` devices.
After that, unfortunately, no more. Does anyone have any idea what the problem is or what I am doing wrong?

I compiled OT with USB CDC ACM support.
Device Info:
```
UF2 Bootloader 0.7.0 lib/nrfx (v2.0.0) lib/tinyusb (0.12.0-145-g9775e7691) lib/uf2 (remotes/origin/configupdate-9-gadbb8c7)
Model: Adafruit Feather nRF52840 Express
Board-ID: nRF52840-Feather-revD
Date: Jul 13 2022
SoftDevice: S140 6.1.1
```

**Comment by canisLupus1313** [comment]
@fklement the board that You are compiling for is not supported in this repository. (Building with `-DOT_BOOTLOADER=USB` IHMO won't help.)
Have You tried using NCS repo instead?
https://github.com/nrfconnect/sdk-nrf
I can see that zephyr should support this board and so NCS.

**Comment by jwhui** [comment]
Closing stale issue.
