### ISSUE TITLE
cant flash nrf52 dongle using nRFconnect for desktop.

### ISSUE THREAD

**Issue by sohaibbinaltaf** [openthread/ot-nrf528xx#451]
I am using nRF52840 dongle with raspberry pi 4 to create a thread network. I downloaded nRFconnect for desktop to flash the hex files into the dongles.

I successfully flashed a dongle when i downloaded a hex file from [https://golioth.github.io/golioth-openthread-demo-docs/docs/create-rcp#build-your-own](url). Its rcp hex file. 

but when i was try to flash the dongle with the hex file generated using [https://openthread.io/codelabs/openthread-border-router-ipv6-multicast#2](url) i was unable to write the hex file. The write option was disabled and could only be used when i select the Enable MCUboot. Not sure why.

When i select Enable MCUboot and try to write the hex file it shows an error,
mcu boot failed with error operation, program not supported error when starting fw program

can you please help me to solve this problem.

i want to to flash both rcp and ot-cli-ftd.hex into the dongles as i need to make a thread network. and if how can i flash the dongle from the raspberry pi command line, what packages i need to install and what commands will be used if i could get this information.

**Comment by jwhui** [comment]
Closing stale issue.
