### ISSUE TITLE
nRF52840-Dongle with dual-bootloader setup

### ISSUE THREAD

**Issue by pepe2k** [openthread/ot-nrf528xx#492]
Hi,

This is more like a question than an real issue for this repository.

I'm looking for a hint with a custom dual-bootloader configuration on the nRF52840 (I'm using the nRF52840-Dongle as a testing device). I would like to keep the generic Nordic's Open USB Bootloader but include another customized bootloader (MCUboot) in the boot chain. The idea is to load MCUboot from the Nordic's Open USB Bootloader (this seems to be working out of the box) and then load OpenThread example by MCUboot. The problem is that I'm not sure what else than memory layout (flash offset and size for linker) should be adjusted?

I'm aware of the Zephyr based nRF Connect SDK where MCUboot is part of it and I have already used it.

Thanks for help!

**Comment by jwhui** [comment]
I would suggest reaching out via [Nordic DevZone](https://devzone.nordicsemi.com/).
