### ISSUE TITLE
/opt/nrfjprog/: No such file or directory

### ISSUE THREAD

**Issue by tunm1228** [openthread/ot-nrf528xx#668]
<img width="1370" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/7fad6bae-76c4-4931-9cda-6dfb0f7cab49">

**Comment by superwhd** [comment]
I wonder if you've done [this step](https://openthread.io/codelabs/openthread-hardware#install-nrf5x-command-line-tools) to install the NRF5x command line tools? `nrfjprog` is part of the tools.

**Comment by tunm1228** [comment]
> I wonder if you've done [this step](https://openthread.io/codelabs/openthread-hardware#install-nrf5x-command-line-tools) to install the NRF5x command line tools? `nrfjprog` is part of the tools.

I haven't done this step yet. I will try. thank you

**Comment by tunm1228** [comment]
> I wonder if you've done [this step](https://openthread.io/codelabs/openthread-hardware#install-nrf5x-command-line-tools) to install the NRF5x command line tools? `nrfjprog` is part of the tools.

May I ask you. Download and push in and do what is in this downloaded file?

**Comment by tunm1228** [comment]
I installed it but still can't find this folder
<img width="1422" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/65b1be48-4bad-4cce-aab8-d18774200415">

**Comment by tunm1228** [comment]
<img width="1389" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/39aaa705-81d0-4eab-ace5-1d57948e8e40">

**Comment by superwhd** [comment]
Could you check `which nrfjprog`? Probably the executable binary already in your `$PATH`.

**Comment by tunm1228** [comment]
<img width="868" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/b19baef7-1ca4-4e5d-885d-f0511631abd4">
it is here

**Comment by superwhd** [comment]
Then you should be able to run `nrfjprog`. Is there specifically anything else you need in the `nrfjprog/` directory?

**Comment by tunm1228** [comment]
Project ot-nrf528xx is in the root directory. Can you guide me to navigate to nrfjprog

**Comment by tunm1228** [comment]
<img width="1149" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/96c2da4b-10b4-440b-8086-64bc7dae7173">
it had this error

**Comment by superwhd** [comment]
Try removing `./` from the beginning of your command.

**Comment by tunm1228** [comment]
<img width="1171" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/87c52d8d-a682-44b4-9b59-09e417df1f14">
still error

**Comment by tunm1228** [comment]
<img width="1252" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/334748c0-8357-430f-a290-ed075b43bd26">

**Comment by tunm1228** [comment]
<img width="1129" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/dd256355-1621-49ce-b703-478d2df0aa14">

**Comment by tunm1228** [comment]
> Try removing `./` from the beginning of your command.

It looks like read back protection (APPROTECT) is enabled. If so, you can disable it using "nrfjprog --recover".
<img width="1179" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/90136c29-533d-4645-a5c6-62f4d1b7e42c">

**Comment by tunm1228** [comment]
@superwhd Do you know what this error is caused by?
<img width="650" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/50b2ade3-00a3-463b-bdcf-ec41b1645c5b">

**Comment by tunm1228** [comment]
I had to unplug and plug it back in for it to work
<img width="960" alt="image" src="https://github.com/openthread/ot-nrf528xx/assets/42457760/abfb26ba-a2f5-4dea-8790-09625a981526">
