### ISSUE TITLE
[build] Compilation error: conflicting types for 'otPlatRadioEnableCsl'

### ISSUE THREAD

**Issue by zwx1995esp** [openthread/ot-nrf528xx#69]
I pull the new code and make the project using:
`./script/build nrf52840 USB_trans -DOT_CSL_RECEIVER=ON -DOT_LINK_METRICS=ON -DOT_DIAGNOSTIC=ON -DOT_THREAD_VERSION=1.2`
and I get a compilation error: conflicting types for 'otPlatRadioEnableCsl'

The cause of the problem seems to be the change in the commit `b0cb90b1`, the definition of function `otPlatRadioEnableCsl` has been changed. 

If I want to use the CSL feature, which parameters need to be added to the compile command?

**Comment by jwhui** [comment]
@zwx1995esp , did you update the git submodule?
```
$ git submodule update
```

**Comment by zwx1995esp** [comment]
Thank you, I am sorry to forget that I did not update the submodule, Now, it works.
