### ISSUE TITLE
How to make ot-br-posix enable OT_BLE_TACT?

### ISSUE THREAD

**Issue by L1amaGod** [openthread/ot-nrf528xx#707]
**Describe the bug** A clear and concise description of what the bug is.
How to make ot-br-posix enable OT_BLE_TACT?

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id : ae6eff5f212d88d86448d4c085d52098babe13a9
2. IEEE 802.15.4 hardware platform : nrf52840
3. Build steps : 
4. Network topology : Thread with ble based commissioning

**Expected behavior** A clear and concise description of what you expected to happen.
Build otbr and run ble based thread commissioning normally

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.
I want to test Ble based thread commissioning, but I don't know the step to build the otbr and do a test.

**Comment by L1amaGod** [comment]
It looks like that it have not been implemented yet.

**Comment by canisLupus1313** [comment]
@L1amaGod Currently the only platform that has the TCAT functionality implemented fully is NCS  please refer to https://github.com/nrfconnect/sdk-nrf .

**Comment by L1amaGod** [comment]
> @L1amaGod Currently the only platform that has the TCAT functionality implemented fully is NCS please refer to https://github.com/nrfconnect/sdk-nrf .

But I can not update to the newest sdk version which includes TCAT features. I typed `west update` to update my ncs, but it could only update to "ncs-zephry: v3.4.99-ncs1-1" which didn't have TCAT features.

![image](https://github.com/openthread/ot-nrf528xx/assets/120552678/74f2f220-77d5-48e2-a239-969dd7747090)


How can I update to the newest version?

**Comment by canisLupus1313** [comment]
@L1amaGod try initialising the west work space from nrf repo
`west init -m https://github.com/nrfconnect/sdk-nrf `
Then do `west update` and build the cli sample with:
`west build -b nrf52840dk_nrf52840 nrf/samples/openthread/cli/  -p always -S="tcat"`

**Comment by L1amaGod** [comment]
> @L1amaGod try initialising the west work space from nrf repo `west init -m https://github.com/nrfconnect/sdk-nrf ` Then do `west update` and build the cli sample with: `west build -b nrf52840dk_nrf52840 nrf/samples/openthread/cli/ -p always -S="tcat"`

@canisLupus1313 Thank you so much! It works. And then could you teach me how can I make my OTBR commission to this ble_tcat thread device by using this ble_tcat feature?

**Comment by canisLupus1313** [comment]
@L1amaGod  On the DK yu should invoke `ot tcat start` via cli.
And use  TCAT commissioner currently we are working on options to deliver but You can look at:

https://github.com/pjasinski990/bbtc
or
https://github.com/arnulfrupp/TcatClient

**Comment by L1amaGod** [comment]
@canisLupus1313 Thank you!So based on current github code, is it possiable for me to do a test about connecting to a tcat device? Because I tried to install bbtc and connected to a tcat device, but I failed.
![image](https://github.com/openthread/ot-nrf528xx/assets/120552678/c6bb5f93-14a7-4aff-9cec-f2e7a453bf3a)

**Comment by canisLupus1313** [comment]
@L1amaGod Have you changed the provided certificates? Or anything in the code?
```
Enter 'help' to see available commands or 'exit' to exit the application.
> scan
Found devices:

1: Thread BLE - E4:08:FD:3E:97:1E

Select the target number to connect to it.
> 1
Selected  E4:08:FD:3E:97:1E: Thread BLE
Connecting to E4:08:FD:3E:97:1E: Thread BLE
Setting up secure channel...
```

In my original one I can also spot that BLE device is named differently `Thread BLE` vs `NCS DUT`.

**Comment by L1amaGod** [comment]
@canisLupus1313 No, I have not changed the provided certificates. The only thing I changed is `name = "bbtc client"` in file `pyproject.toml`. 
Because I failed in `poetry install` at the begining. The logs is like below:
![image](https://github.com/openthread/ot-nrf528xx/assets/120552678/279cd465-dca6-4389-9e9f-bca21a716e9a)

And then I changed `name = "bbtc client"` to `name = "bbtc"` in file `pyproject.toml`. Is that the reason I can not connect device?

**Comment by canisLupus1313** [comment]
@L1amaGod I was asking about the firmware that you have. Since name of the device is changed there. 
And the default certificated are compiled into the device.

**Comment by L1amaGod** [comment]
@canisLupus1313 OK, I have uploaded my firmware. Please have a look.

**Comment by canisLupus1313** [comment]
@L1amaGod 
[zephyr.hex.zip](https://github.com/openthread/ot-nrf528xx/files/13751089/zephyr.hex.zip)
Please try this firmware.
And Can You upload your `.config` file from zephyr build repo?

**Comment by L1amaGod** [comment]
> @L1amaGod [zephyr.hex.zip](https://github.com/openthread/ot-nrf528xx/files/13751089/zephyr.hex.zip) Please try this firmware. And Can You upload your `.config` file from zephyr build repo?

Of course.
```
## ../nrf/samples/openthread/cli/prj.conf

#
# Copyright (c) 2020 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

# Enable OpenThread features set
CONFIG_OPENTHREAD_NORDIC_LIBRARY_MASTER=y

CONFIG_NET_L2_OPENTHREAD=y

# Generic networking options
CONFIG_NETWORKING=y

CONFIG_MBEDTLS_SHA1_C=n
CONFIG_FPU=y

CONFIG_GPIO_SHELL=y

#Added
CONFIG_OPENTHREAD_BLE_TCAT=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2144
CONFIG_BT=y
CONFIG_BT_HCI=y
CONFIG_BT_SHELL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="NCS DUT"
CONFIG_BT_DEVICE_APPEARANCE=833

```

**Comment by L1amaGod** [comment]
Maybe I found the reason. I used to build cli project with `west build -b nrf52840dk_nrf52840` after I modified file `prj.conf`, but it failed in tcat connection.
Now I build project with `west build -b nrf52840dk_nrf52840 nrf/samples/openthread/cli/  -p always -S="tcat"` as you said, and now it works normally.

**Comment by canisLupus1313** [comment]
@L1amaGod 
Good reference would be reading about snippets https://docs.zephyrproject.org/latest/build/snippets/index.html

The one that is actually enabling the TCAT is https://github.com/nrfconnect/sdk-nrf/blob/main/samples/openthread/cli/snippets/tcat/

**Comment by canisLupus1313** [comment]
@L1amaGod have You had a chance to read the above docs? do You have any more questions?

**Comment by jwhui** [comment]
Closing stale issue.
